title: GBM CV | A jekyll template
description:  A beautiful template for your CV.
url: http://www.igvir.com/gbm-cv/
baseurl: 'gbm-cv'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
